name: "Test EM27 Metadata Storage"
author: "Moritz Makowski <moritz.makowski@tum.de>"
description: "Test the integrity of a repository containing EM27 metadata"
runs:
  using: "composite"
  steps:
    # move all library files into working directory; this makes
    # testing easier because we don't have to worry about
    # different paths for the repo and the action.
    - name: Copy action files
      run: |
        cp -r ${{ github.action_path }}/tests .
        cp -r ${{ github.action_path }}/em27_metadata .
        cp ${{ github.action_path }}/pyproject.toml .
      shell: bash

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    # install dependencies if cache does not exist
    - name: Install dependencies
      run: pip install ".[dev]"
      shell: bash

    # run tests
    - name: Run pytests
      env:
        GITHUB_REPOSITORY: ${{ github.action_repository }}
        GITHUB_ACCESS_TOKEN: ${{ github.token }}
      run: python -m pytest tests/ -m "action"
      shell: bash
