name: "test"
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        id: setup-python-env
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"

      # install & configure poetry if cache does not exist
      - name: Install dependencies
        run: pip install ".[dev]"

      # run tests
      - name: Run pytests
        env:
          GITHUB_REPOSITORY: ${{ github.action_repository }}
          GITHUB_ACCESS_TOKEN: ${{ github.token }}
        run: python -m pytest tests/ -m "library"

      - name: Check whether code formatting is correct
        run: |
          python -m yapf em27_metadata --recursive --quiet
          python -m yapf tests --recursive --quiet
